instagram_web/blueprints/users/views.py
import os
from flask import Blueprint, render_template,request,url_for,redirect, flash
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from models import *
from models.followers import *
from flask_wtf.csrf import CSRFProtect
from flask_login import login_user,current_user
from instagram_web.util.helpers import *
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from datetime import datetime




users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


now = datetime.now()
timestamp = datetime.timestamp(now)

@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    name_input = request.form.get('name_input')
    email_input = request.form.get('email_input')
    username_input = request.form.get('username_input')
    password_input = request.form.get('password_input')
    
    new_user = user.User(name=name_input, email=email_input, username=username_input, password=password_input)

    if new_user.save():
        # return redirect(url_for('users.index')) #use when done with signup 
        login_user(new_user)
        return redirect(('/'))
    else:
        for e in new_user.errors:
            flash(e)
        return render_template('users/new.html', email_input=email_input, name_input=name_input,password_input=password_input,username_input=username_input, errors=new_user.errors)


@users_blueprint.route('/<username>/show', methods=["GET"])
def show(username):
    # user profile of visited user
    user_profile = user.User.get_or_none(user.User.username == username)

    # if current user is logged in
    if current_user.is_authenticated:
        # if visited user exist
        if user.User.get_or_none(user.User.username == username):
            # if current user is current user
            if current_user.username == username:
                img = user.User.get_by_id(current_user.id).images
                return render_template('users/my_profile.html', img = img)
            else:
                # check if current user is following visited user
                following = ""
                if Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == user_profile.id):
                    following = True
                else:
                    following = False 

                img = user.User.get_by_id(user_profile.id).images
                return render_template('users/profile.html', user_profile= user_profile, img = img, following = following)
        else:
            return render_template('/users/user_doesnt_exist.html')
    else:
        return render_template('/users/not_logged_in.html')
    


@users_blueprint.route('/', methods=["GET"])
def index():
    allfollowers = []
    
    for f in current_user.followers:
        status = False
        follower_profile = user.User.get_by_id(f.follower)
        if Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == follower_profile.id):
            status = True
        allfollowers.append({
            "profile" : follower_profile,
            "status": status
        })
        
    return render_template("users/user_list.html", allfollowers=allfollowers)


@users_blueprint.route('/edit', methods=['GET'])
def edit():
    return render_template('users/edit.html')


@users_blueprint.route('/edit', methods=['POST'])
def update():
    email_edit_input = request.form.get('email_edit_input')
    username_edit_input = request.form.get('username_edit_input')
    # password_edit_input = request.form.get('password_edit_input')
    
    new_info = user.User.update(username= username_edit_input, email=email_edit_input).where(user.User.id == current_user.id)

    new_info.execute()
    return redirect(url_for('home'))
    
@users_blueprint.route('/edit/password', methods=["GET"])
def password():
    return render_template('users/edit_password.html')

@users_blueprint.route('/edit/password', methods=["POST"])
def edit_password():
    current_password = request.form.get('current_password')
    new_password = request.form.get('new_password')
    comfirm_password = request.form.get('comfirm_password')
    
    if check_password_hash(current_user.password, current_password):
        if current_password == comfirm_password or current_password == new_password:
            flash("Current password and new password are the same")
            return render_template('users/edit_password.html')
        elif comfirm_password == new_password:
            hashed_password = generate_password_hash(new_password)
            new_info = user.User.update(password = hashed_password).where(user.User.id == current_user.id)
            
            new_info.execute()
            return redirect(url_for('home'))
        else:
            flash('New passsword and comfirm password is not the same')
            return render_template('users/edit_password.html')
    else:
        flash('Wrong password')
        return render_template('users/edit_password.html')
        

@users_blueprint.route('/profile_image', methods=["GET"])
def profile():
    if current_user.is_active:
        return render_template('users/profile_image.html')
    else:
        return redirect(url_for('home'))

@users_blueprint.route('/profile_image', methods=["POST"])
def upload():
    
    if "user_file" not in request.files:
        return "No user_file key in request.files"
    
    file = request.files['user_file']
    if file.filename == "":
        return "Please select a file"

    if file and allowed_file(file.filename):
        file.filename = secure_filename(file.filename)
        output = upload_file_to_s3(file,S3_BUCKET)

        profile_image_url = str(output)
        new_image = user.User.update(profile_image = profile_image_url ).where(user.User.id == current_user.id)
        new_image.execute()
        return redirect(url_for('home'))
        
    else:
        return redirect(url_for('home'))


@users_blueprint.route('/upload_image', methods=["GET"])
def images():
    return render_template('users/upload_image.html')

@users_blueprint.route('/upload_image', methods=["POST"])
def upload_user_images():
    if "user_file" not in request.files:
        return "No user_file key in request.files"
    
    file = request.files['user_file']
    if file.filename == "":
        return "Please select a file"

    if file and allowed_file(file.filename):
        file.filename = secure_filename(file.filename)
        output = upload_file_to_s3(file,S3_BUCKET)
        image_url = str(output)
        image_description = request.form.get('image_description')
        user_images.User_images.create(user=current_user.id,image=image_url,description=image_description)
        
        # delete create later on so u can save and validate
        return redirect(url_for('home'))
        
    else:
        return redirect(url_for('home'))

@users_blueprint.route('/search',methods=["GET"])
def search():
     search_username = request.args.get("search_username")
     return redirect(url_for('users.show', username = search_username))

@users_blueprint.route('/private', methods=["POST"])
def make_private():
    
    x = user.User.update(is_private = not current_user.is_private).where(user.User.id == current_user.id)
    x.execute()
    if current_user.is_private:
        flash("Account set to public")
    else:
        flash("Account set to private")

    
    return redirect(url_for('users.show', username = current_user.username))
    
@users_blueprint.route('/follow/<username>', methods=["POST"])
def follow(username):
    pending = False
    user_profile = user.User.get_or_none(user.User.username == username)

    # if profile exist
    if user_profile:
        # if profile is private
        if user_profile.is_private:
            message = Mail(
                from_email='NazNextagram@gmail.com',
                to_emails="upchuck333@yahoo.com",
                subject="You've received a donation!",
                html_content=render_template("users/follow_request.html", timestamp = timestamp,user_profile = user_profile))
            try:
                sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                response = sg.send(message)
                print(response.status_code)
                print(response.body)
                print(response.headers)
            except Exception as e:
                print(str(e))

            pending = True
            flash("follow request sent")
            return render_template("/users/profile.html", user_profile = user_profile, pending = pending)
        # if profile public
        else:
            following = Followers(follower = current_user.id, followed = user_profile.id).save() 
            return redirect(url_for('users.show', username = username))
    # if user doesnt exist
    else:
        return render_template('/users/user_doesnt_exist.html')
    
@users_blueprint.route(f"/follow/private/<username>/{timestamp}", methods=["GET"])
def follow_request(username):
    user_profile = user.User.get_or_none(user.User.username == username)
    following = Followers(follower = current_user.id, followed = user_profile.id).save() 
    
    return redirect(url_for("home"))

@users_blueprint.route('/unfollow/<username>', methods=["POST"])
def unfollow(username):
    followed_user = user.User.get_or_none(user.User.username == username)
    unfollowed = Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == followed_user.id).delete_instance()
    # if unfollowed:
    #     flash("Unfollowed")
    # else:
    #     flash("Something went wrong")
    return redirect(url_for('home'))

instagram_web/blueprints/users/templates/users/edit.html
{% extends "_layout.html" %} {% block navbar%} {%endblock%} {%block content%}
<h1 style="margin: 10vh 0 0 5vw ;">
  Edit Profile
</h1>
<form action="{{url_for('users.edit')}}" method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <div style="display: flex; flex-direction: column; margin: 3vh 0 0 5vw;">
    <p style="margin: 2vh 0 0 0;">Current Email :</p>
    <label for="email_edit_input" style="margin: 2vh 0 0 4.5vw;"></label>
    <input
      type="email"
      name="email_edit_input"
      placeholder="{{current_user.email}}"
      style="border: none; width: 40vw;"
      value="{{current_user.email}}"
    />
    <p style="margin: 2vh 0 0 0;">Current Username :</p>

    <label for="email_edit_input" style="margin: 2vh 0 0 4.5vw;"></label>
    <input
      type="text"
      name="username_edit_input"
      placeholder="{{current_user.username}}"
      style="border: none; width: 40vw;"
      value="{{current_user.username}}"
    />
    <button
      type="submit"
      style=" margin:3vh 0 0 0;width: 12vw; height:4.5vh;border-radius: 4px;cursor: pointer;background-color: #3897f0; color: white;border: none;"
    >
      Edit
    </button>
  </div>
</form>
{%endblock%}

instagram_web/blueprints/users/templates/users/edit_password.html
{% extends "_layout.html" %} {% block navbar%} {%endblock%} {%block content%}
<h1 style="margin: 10vh 0 0 5vw ;">
  Edit Profile
</h1>

<form action="{{url_for('users.password')}}" method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <div style="display: flex; flex-direction: column; margin: 3vh 0 0 5vw;">
    <p style="margin: 2vh 0 0 0;">Current Password :</p>

    <label for="current_password" style="margin: 2vh 0 0 4.5vw;"></label>
    <input
      name="current_password"
      type="password"
      placeholder="current_password"
      style="border: none; width: 40vw;"
    />
    <p style="margin: 2vh 0 0 0;">New Password :</p>

    <label for="new_password" style="margin: 2vh 0 0 4.5vw;"></label>
    <input
      name="new_password"
      type="password"
      placeholder="new password"
      style="border: none; width: 40vw;"
    />
    <p style="margin: 2vh 0 0 0;">Comfirm Password :</p>

    <label for="comfirm_password" style="margin: 2vh 0 0 4.5vw;"></label>
    <input
      name="comfirm_password"
      type="password"
      name="email_edit_input"
      placeholder="comfirm password"
      style="border: none; width: 40vw;"
    />
    <button
      type="Summit"
      type="submit"
      style=" margin: 3vh 0 0 0;width: 12vw; height:4.5vh;border-radius: 4px;cursor: pointer;background-color: #3897f0; color: white;border: none;"
    >
      Edit
    </button>
  </div>
</form>
{%endblock%}

instagram_web/blueprints/users/templates/users/my_profile.html
{%extends "_layout.html"%} {%block content%}
<style>
  #current_user_profile_image:hover {
    opacity: 0.5;
    filter: blur(1px);
    -webkit-filter: grayscale(30%);
  }
  #current_user_profile_image_container:hover {
    opacity: 0.5;
    filter: blur(1px);
    -webkit-filter: grayscale(30%);
  }
</style>

<div style="background-color: #fafafa;">
  <div
    style="display: flex; flex-direction: row; margin: 0vh 5vw 0 5vw; padding: 5vh 0 0 0;"
  >
    <a href="{{url_for('users.profile')}}">
      <img
        id="current_user_profile_image"
        src="{{current_user.image_path}}"
        alt=""
        style="width: 200px;height: 200px; border-radius: 50%; text-align: center; cursor: pointer;"
      />
    </a>

    <div style="display: flex;flex-direction: column;">
      <div style="display: flex;flex-direction: row;">
        <p style="margin: 1vh 0 0 5vw ; font-size: 35px; font-weight: 100;">
          {{current_user.username}}
        </p>
        <form action="{{url_for('users.edit')}}">
          <button
            style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: white; color: black; margin: 3vh 0 0 7vw; border: none;border-color: #b3b3b3; border-style: solid;border-width: 1px; outline: none;"
          >
            Edit
          </button>
        </form>
        <!-- <form action="{{url_for('users.make_private')}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button
          style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: white; color: black; margin: 3vh 0 0 7vw; border: none;border-color: #b3b3b3; border-style: solid;border-width: 1px;"
        >
          Make Private
        </button>
      </form>

      <form action="{{url_for('users.images')}}">
        <button
          style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: white; color: black; margin: 3vh 0 0 7vw; border: none;border-color: #b3b3b3; border-style: solid;border-width: 1px;"
        >
          Upload
        </button>
      </form> -->
      </div>
      <div style="display: flex;flex-direction: row; margin: 1vh 0 0 5vw;">
        <p style="font-size: 18px;">{{img|length}}</p>
        <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300 ;">
          Post
        </p>

        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{current_user.followers |length}}
        </p>
        <a
          href="{{url_for('users.index')}}"
          style="color: black; text-decoration: none;"
        >
          <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300;">
            Followers
          </p>
        </a>
        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{current_user.following |length}}
        </p>
        <p style="margin: 0 0 0 0.5vw;font-size: 18px;font-weight: 300;">
          Following
        </p>
      </div>
      <div style="font-size: 18px; margin: 0 0 0 5vw;">
        <p>{{current_user.name}}</p>
      </div>
    </div>
  </div>

  <div style="margin: 5vh 0 0 2vw;">
    <div
      style="display: flex;flex-direction: row; ; margin: auto; flex-wrap: wrap;"
    >
      {%for i in img%}
      <div>
        <img
          src="{{i.image_path}}"
          alt=""
          style="width: 30vw;height: 30vw; margin: 1vw; object-fit: cover;"
        />
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{%endblock%}

instagram_web/blueprints/users/templates/users/new.html
{% extends '_layout.html' %} {%block navbar%} {%endblock%} {%block content%}
<div style="background-color: #fafafa; width: 100vw;height: 100vh;">
  <div
    style="position: absolute; top: 40%;left: 50%;transform: translate(-50%,-50%); width: 30vw; height: 55vh;border: 1px solid #c2c2c2;border-radius: 2px;background-color: white;"
  >
  <p style="text-align: center; margin: 5vh 0 0 0; font-size: 35px;">Nextagram</p>
  <div style="margin: 3vh 0 0 0;">
    <form
      action="{{url_for('users.create')}}"
      method="POST"
      style="margin: 0 0 0 5vw;"
    >
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <div style="display: flex; flex-direction: column;">
        <input placeholder="Name"type="text" name="name_input" style="width: 20vw; border-radius: 3px; border: 1px solid #d3d3d3; height: 35px; font-size: 13px; padding: 0 0 0 1vw;background-color: #fafafa; margin: 1vh 0 0 " />
      </div>
      <div style="display: flex; flex-direction: column;">
        <input placeholder="Email" type="email" name="email_input" style="width: 20vw; border-radius: 3px; border: 1px solid #d3d3d3; height: 35px; font-size: 13px; padding: 0 0 0 1vw;background-color: #fafafa; margin: 1vh 0 0 " />
        <!-- change type back to email  -->
      </div>
      <div style="display: flex; flex-direction: column;">
        <input placeholder="Username" type="text" name="username_input" style="width: 20vw; border-radius: 3px; border: 1px solid #d3d3d3; height: 35px; font-size: 13px; padding: 0 0 0 1vw;background-color: #fafafa; margin: 1vh 0 0 " />
      </div>
      <div style="display: flex; flex-direction: column;">
        <input placeholder="Password" type="password" name="password_input" style="width: 20vw; border-radius: 3px; border: 1px solid #d3d3d3; height: 35px; font-size: 13px; padding: 0 0 0 1vw;background-color: #fafafa; margin: 1vh 0 0 " />
      </div>
      <button
        type="submit"
        style="width: 20vw; height: 35px; border-radius: 4px; cursor: pointer; background-color: #3897f0; color: white; margin: 3vh 0 2vh 0vw; border: none;"
      >
        Sign Up
      </button>
    </form>
    </div>
  </div>

  <div
  style="position: absolute; top: 73%;left: 50%;transform: translate(-50%,-50%); width: 30vw; height: 10vh;border: 1px solid #c2c2c2;border-radius: 2px;background-color: white;"
  >
    <div style="margin: 3vh 0 0 0vw;display: flex;justify-content: center;">
      <p>Have an account?</p>
      <a href="{{url_for('sessions.new')}}"
        ><p style="margin: 0 0 0 0.5vw;">Log in</p></a
      >
    </div>
  </div
  >
</div>
</div>
{%endblock%}

instagram_web/blueprints/users/templates/users/not_logged_in.html
{% extends "_layout.html" %} {% block title %}Page Not Found{% endblock %}
{%block navbar%} {%endblock%} {%block content %}
<div style="position: relative;">
  <h1
    style="position: absolute;top: 20vh;left: 50%;transform: translate(-50%,0);font-size: 45px;"
  >
    Not logged in
  </h1>
  <p
    style="position: absolute;top: 28vh;left: 50%;transform: translate(-50%,0);font-size: 18px;text-align: center;margin: 2vh 0 0 0;"
  >
    To view this page you need to make an account first :)
  </p>
  <a
    style="position: absolute;top: 36.5vh;left: 50%;transform: translate(-50%,0);font-size: 18px;text-align: center;margin: 2vh 0 0 0;text-decoration: none;"
    href="{{url_for('users.new')}}"
    ><p>Create an account</p></a
  >
</div>
{% endblock %}

instagram_web/blueprints/users/templates/users/profile.html
{%extends "_layout.html"%} {%block content%} {%if user_profile.is_private and
not following %}

<!-- private profile -->

<div style="background-color: #fafafa;min-height: 105vh;">
  <div
    style="display: flex; flex-direction: row; margin: 0vh 0 0 5vw; padding: 5vh 0 0 0;"
  >
    <img
      src="{{user_profile.image_path}}"
      alt=""
      style="width: 200px;height: 200px; border-radius: 50%; text-align: center; "
    />
    <div style="display: flex;flex-direction: column;">
      <div style="display: flex; flex-direction: row;">
        <p style="margin: 1vh 0 0 5vw ; font-size: 35px; font-weight: 100;">
          {{user_profile.username}}
        </p>
        <form
          action="{{url_for('users.follow', username=user_profile.username)}}"
          method="POST"
        >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button
            style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: #3897f0; color: white; margin: 3vh 0 0 7vw; border: none; outline: none;"
          >
            Follow
          </button>
        </form>
      </div>
      <div style="display: flex;flex-direction: row; margin: 1vh 0 0 5vw;">
        <p style="font-size: 18px;">{{img|length}}</p>
        <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300 ;">
          Post
        </p>
        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{user_profile.followers |length}}
        </p>
        <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300;">
          Followers
        </p>
        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{user_profile.following |length}}
        </p>
        <p style="margin: 0 0 0 0.5vw;font-size: 18px;font-weight: 300;">
          Following
        </p>
      </div>
      <div>
        <p style="font-size: 18px; margin: 0 0 0 5vw;">{{user_profile.name}}</p>
      </div>
    </div>
  </div>

  <div
    style="display: flex; justify-content: center; flex-direction: row; margin: 5vh 0 0 0;"
  >
    <p style="font-size: 25px; text-align: center;">
      This account is private
    </p>
  </div>

  <div
    style="display: flex; justify-content: center; flex-direction: row; margin: 1vh 0 0 0;"
  >
    <p style="font-size: 20px; text-align: center;">
      Follow this user to see their photos and videos
    </p>
  </div>
</div>
{%else%}
<!-- public profile -->
<style>
  #Follow_button:hover span {
    display: none;
  }
  #Follow_button:hover:before {
    content: "Unfollow";
  }
</style>
<div style="background-color: #fafafa;min-height: 105vh;">
  <div
    style="display: flex; flex-direction: row; margin: 0vh 0 0 5vw; padding: 5vh 0 0 0;"
  >
    <img
      src="{{user_profile.image_path}}"
      alt=""
      style="width: 200px;height: 200px; border-radius: 50%; text-align: center; "
    />

    <div style="display: flex; flex-direction: column;">
      <div style="display: flex; flex-direction: row;">
        <p style="margin: 1vh 0 0 5vw ; font-size: 35px; font-weight: 100;">
          {{user_profile.username}}
        </p>

        {% if following %}
        <form
          action="{{url_for('users.unfollow', username=user_profile.username)}}"
          method="POST"
        >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button
            id="Follow_button"
            style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: white; color: black; margin: 3vh 0 0 7vw; border: none;border-color: #b3b3b3; border-style: solid;border-width: 1px;"
          >
            <span>Following</span>
          </button>
        </form>
        {% else %}
        <form
          action="{{url_for('users.follow', username=user_profile.username)}}"
          method="POST"
        >
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <button
            style="width: 90px; height: 30px; border-radius: 4px; cursor: pointer; background-color: #3897f0; color: white; margin: 3vh 0 0 7vw; border: none;outline: none;"
          >
            Follow
          </button>
        </form>
        {% endif %}
      </div>
      <div style="display: flex;flex-direction: row; margin: 1vh 0 0 5vw;">
        <p style="font-size: 18px;">{{img|length}}</p>
        <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300 ;">
          Post
        </p>
        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{user_profile.followers |length}}
        </p>
        <p style="margin: 0 0 0 0.5vw; font-size: 18px;font-weight: 300;">
          Followers
        </p>
        <p style="font-size: 18px;margin: 0 0 0 8vw;">
          {{user_profile.following |length}}
        </p>
        <p style="margin: 0 0 0 0.5vw;font-size: 18px;font-weight: 300;">
          Following
        </p>
      </div>
      <div>
        <p style="font-size: 18px; margin: 0 0 0 5vw;">{{user_profile.name}}</p>
      </div>
    </div>
  </div>

  <div style="margin: 5vh 0 0 0;">
    <div
      style="display: flex;flex-direction: row; justify-content: space-around; margin: auto;"
    >
      {%if img | length < 1 %}
      <p style="font-size: 25px; text-align: center;">
        No posts yet
      </p>
      {%else%} {%for i in img%}
      <div>
        <img
          src="{{i.image_path}}"
          alt=""
          style="width: 30vw;height: 30vw; margin: 1vw; object-fit: cover;"
        />
        <script src="https://js.braintreegateway.com/web/dropin/1.22.0/js/dropin.min.js"></script>
        <div id="dropin-container"></div>

        <form action="{{url_for('payment.new_payment', img_id = i.id)}}">
          <button
            id="submit-button"
            style="width: 30vw;height: 40px; margin: 1vw; border-radius: 4px; background-color: #007BFF; color: white; cursor: pointer; border: none;"
          >
            Donate
          </button>
        </form>
      </div>
      {% endfor %} {%endif%}
    </div>
  </div>
</div>
{%endif%} {%endblock%}

instagram_web/blueprints/users/templates/users/profile_image.html
{% extends "_layout.html" %}{%block content%}
<div style="margin: 2vh 0 0 5vw;">
  <h1>Change Profile Image</h1>

  <form
    action="{{url_for('users.profile')}}"
    method="POST"
    enctype="multipart/form-data"
    style="margin: 5vh 0 0 0 ;"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <label for="user_file"> </label>

    <input type="file" name="user_file" />
    <button type="submit">Upload</button>
  </form>
</div>
{%endblock%}

instagram_web/blueprints/users/templates/users/upload_image.html
{% extends "_layout.html" %}{%block content%}
<div style="margin: 2vh 0 0 5vw;">
  <h1>Upload Image</h1>

  <form
    action="{{url_for('users.images')}}"
    method="POST"
    enctype="multipart/form-data"
    style="margin: 5vh 0 0 0 ;"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <label for="user_file"> </label>

    <input type="file" name="user_file" />

    <label for="image_description"></label>
    <input type="text" name="image_description" placeholder="Description" />
    <button type="submit">Upload</button>
  </form>
</div>
{%endblock%}

instagram_web/blueprints/users/templates/users/user_list.html
{%extends "_layout.html"%}{%block content%}
<!-- print out follower list -->

<div style="margin: 5vh 5vw 0 5vw;">
  {%for f in allfollowers%}
  <div
    style="display: flex; flex-direction: row; margin: 0 0 2vh; border-bottom: solid 1px #c2c2c2;height: 8vh; justify-content: space-between;"
  >
    <div style="display: flex; flex-direction: row;">
      <a href="{{url_for('users.show', username = f.profile.username)}}">
        <img
          src="{{f.profile.image_path}}"
          alt="profile_image"
          style="width: 45px;height: 45px; border-radius: 50%; border: solid 1px #c2c2c2; cursor: pointer;"
        />
      </a>

      <div style="display: flex; flex-direction: column; margin: 0 0 0 2vw;">
        <a
          href="{{url_for('users.show', username = f.profile.username)}}"
          style="color: black;text-decoration: none;"
        >
          <p style="margin: 0;font-size: 15px;">{{f.profile.username}}</p>
        </a>
        <p style="margin:0;font-size: 15px;color: #c2c2c2;">
          {{f.profile.name}}
        </p>
      </div>
    </div>
    <div style="margin: 1vh 0 0 0 ;">
      {%if f.status%}
      <form
        action="{{url_for('users.unfollow', username = f.profile.username)}}"
        method="POST"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button
          type="submit"
          style="border-radius: 4px; width: 110px; color: black; border: 1px solid #c3c3c3; outline: none; cursor: pointer;"
        >
          Following
        </button>
      </form>
      {%else%}

      <form
        action="{{url_for('users.follow', username = f.profile.username)}}"
        method="POST"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button
          type="submit"
          style="border-radius: 4px; width: 110px; color: white; background-color: #3897f0; border: none; outline: none; cursor: pointer;"
        >
          Follow
        </button>
      </form>
      {%endif%}
    </div>
  </div>
  {%endfor%}
</div>

{%endblock%}