instagram_web/blueprints/users/views.py
import os
from flask import Blueprint, render_template,request,url_for,redirect, flash
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from models import *
from models.followers import *
from flask_wtf.csrf import CSRFProtect
from flask_login import login_user,current_user
from instagram_web.util.helpers import *
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from datetime import datetime




users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


now = datetime.now()
timestamp = datetime.timestamp(now)

@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    name_input = request.form.get('name_input')
    email_input = request.form.get('email_input')
    username_input = request.form.get('username_input')
    password_input = request.form.get('password_input')
    
    new_user = user.User(name=name_input, email=email_input, username=username_input, password=password_input)

    if new_user.save():
        # return redirect(url_for('users.index')) #use when done with signup 
        login_user(new_user)
        return redirect(('/'))
    else:
        for e in new_user.errors:
            flash(e)
        return render_template('users/new.html', email_input=email_input, name_input=name_input,password_input=password_input,username_input=username_input, errors=new_user.errors)


@users_blueprint.route('/<username>/show', methods=["GET"])
def show(username):
    # user profile of visited user
    user_profile = user.User.get_or_none(user.User.username == username)

    # if current user is logged in
    if current_user.is_authenticated:
        # if visited user exist
        if user.User.get_or_none(user.User.username == username):
            # if current user is current user
            if current_user.username == username:
                img = user.User.get_by_id(current_user.id).images
                return render_template('users/my_profile.html', img = img)
            else:
                # check if current user is following visited user
                following = ""
                if Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == user_profile.id):
                    following = True
                else:
                    following = False 

                img = user.User.get_by_id(user_profile.id).images
                return render_template('users/profile.html', user_profile= user_profile, img = img, following = following)
        else:
            return render_template('/users/user_doesnt_exist.html')
    else:
        return render_template('/users/not_logged_in.html')
    


@users_blueprint.route('/', methods=["GET"])
def index():
    allfollowers = []
    
    for f in current_user.followers:
        status = False
        follower_profile = user.User.get_by_id(f.follower)
        if Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == follower_profile.id):
            status = True
        allfollowers.append({
            "profile" : follower_profile,
            "status": status
        })
        
    return render_template("users/user_list.html", allfollowers=allfollowers)


@users_blueprint.route('/edit', methods=['GET'])
def edit():
    return render_template('users/edit.html')


@users_blueprint.route('/edit', methods=['POST'])
def update():
    email_edit_input = request.form.get('email_edit_input')
    username_edit_input = request.form.get('username_edit_input')
    # password_edit_input = request.form.get('password_edit_input')
    
    new_info = user.User.update(username= username_edit_input, email=email_edit_input).where(user.User.id == current_user.id)

    new_info.execute()
    return redirect(url_for('home'))
    
@users_blueprint.route('/edit/password', methods=["GET"])
def password():
    return render_template('users/edit_password.html')

@users_blueprint.route('/edit/password', methods=["POST"])
def edit_password():
    current_password = request.form.get('current_password')
    new_password = request.form.get('new_password')
    comfirm_password = request.form.get('comfirm_password')
    
    if check_password_hash(current_user.password, current_password):
        if current_password == comfirm_password or current_password == new_password:
            flash("Current password and new password are the same")
            return render_template('users/edit_password.html')
        elif comfirm_password == new_password:
            hashed_password = generate_password_hash(new_password)
            new_info = user.User.update(password = hashed_password).where(user.User.id == current_user.id)
            
            new_info.execute()
            return redirect(url_for('home'))
        else:
            flash('New passsword and comfirm password is not the same')
            return render_template('users/edit_password.html')
    else:
        flash('Wrong password')
        return render_template('users/edit_password.html')
        

@users_blueprint.route('/profile_image', methods=["GET"])
def profile():
    if current_user.is_active:
        return render_template('users/profile_image.html')
    else:
        return redirect(url_for('home'))

@users_blueprint.route('/profile_image', methods=["POST"])
def upload():
    
    if "user_file" not in request.files:
        return "No user_file key in request.files"
    
    file = request.files['user_file']
    if file.filename == "":
        return "Please select a file"

    if file and allowed_file(file.filename):
        file.filename = secure_filename(file.filename)
        output = upload_file_to_s3(file,S3_BUCKET)

        profile_image_url = str(output)
        new_image = user.User.update(profile_image = profile_image_url ).where(user.User.id == current_user.id)
        new_image.execute()
        return redirect(url_for('home'))
        
    else:
        return redirect(url_for('home'))


@users_blueprint.route('/upload_image', methods=["GET"])
def images():
    return render_template('users/upload_image.html')

@users_blueprint.route('/upload_image', methods=["POST"])
def upload_user_images():
    if "user_file" not in request.files:
        return "No user_file key in request.files"
    
    file = request.files['user_file']
    if file.filename == "":
        return "Please select a file"

    if file and allowed_file(file.filename):
        file.filename = secure_filename(file.filename)
        output = upload_file_to_s3(file,S3_BUCKET)
        image_url = str(output)
        image_description = request.form.get('image_description')
        user_images.User_images.create(user=current_user.id,image=image_url,description=image_description)
        
        # delete create later on so u can save and validate
        return redirect(url_for('home'))
        
    else:
        return redirect(url_for('home'))

@users_blueprint.route('/search',methods=["GET"])
def search():
     search_username = request.args.get("search_username")
     return redirect(url_for('users.show', username = search_username))

@users_blueprint.route('/private', methods=["POST"])
def make_private():
    
    x = user.User.update(is_private = not current_user.is_private).where(user.User.id == current_user.id)
    x.execute()
    if current_user.is_private:
        flash("Account set to public")
    else:
        flash("Account set to private")

    
    return redirect(url_for('users.show', username = current_user.username))
    
@users_blueprint.route('/follow/<username>', methods=["POST"])
def follow(username):
    pending = False
    user_profile = user.User.get_or_none(user.User.username == username)

    # if profile exist
    if user_profile:
        # if profile is private
        if user_profile.is_private:
            message = Mail(
                from_email='NazNextagram@gmail.com',
                to_emails="upchuck333@yahoo.com",
                subject="You've received a donation!",
                html_content=render_template("users/follow_request.html", timestamp = timestamp,user_profile = user_profile))
            try:
                sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                response = sg.send(message)
                print(response.status_code)
                print(response.body)
                print(response.headers)
            except Exception as e:
                print(str(e))

            pending = True
            flash("follow request sent")
            return render_template("/users/profile.html", user_profile = user_profile, pending = pending)
        # if profile public
        else:
            following = Followers(follower = current_user.id, followed = user_profile.id).save() 
            return redirect(url_for('users.show', username = username))
    # if user doesnt exist
    else:
        return render_template('/users/user_doesnt_exist.html')
    
@users_blueprint.route(f"/follow/private/<username>/{timestamp}", methods=["GET"])
def follow_request(username):
    user_profile = user.User.get_or_none(user.User.username == username)
    following = Followers(follower = current_user.id, followed = user_profile.id).save() 
    
    return redirect(url_for("home"))

@users_blueprint.route('/unfollow/<username>', methods=["POST"])
def unfollow(username):
    followed_user = user.User.get_or_none(user.User.username == username)
    unfollowed = Followers.get_or_none(Followers.follower == current_user.id, Followers.followed == followed_user.id).delete_instance()
    # if unfollowed:
    #     flash("Unfollowed")
    # else:
    #     flash("Something went wrong")
    return redirect(url_for('home'))

instagram_web/templates/_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='image/favicon.ico') }}"
    />

    {% assets "home_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %} {% assets "home_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %} {% block header %} {% endblock %}
    <title>
      {% block title %} {% endblock %}Nextagram
    </title>
  </head>
  <style>
    .google_sign_in {
      margin: 0 2vw 0 0;
      color: #ed4956;
    }
    .google_sign_in:hover {
      color: #be3944;
      border-bottom-color: #ed4956;
    }
    #Nextagram_text:hover {
      color: black;
      text-decoration: none;
    }
  </style>
  <body>
    {% block navbar %}

    <nav
      style="display: flex; flex-direction: row;padding: 2vh 2vw 0.5vh 2vw; justify-content: space-between;border-bottom: 1px solid #c3c3c3;position: fixed;width: 100%;background-color: white;"
    >
      <div style="display: flex; flex-direction: row;">
        <a href="{{url_for('home')}}">
          <img
            src="/static/images/InstagramIcon.png"
            alt=""
            style="width: 30px;height: 30px;cursor: pointer;"
          />
        </a>
        <div
          style="width: 1px;height: 30px;background-color: #c2c2c2; margin: 0 0 0 1vw;"
        ></div>
        <a id="Nextagram_text" href="{{url_for('home')}}">
          <p
            style="cursor: pointer;font-size: 18px;margin: 0 0 0 1vw; color: black;"
          >
            Nextagram
          </p>
        </a>
      </div>
      <div>
        <form action="{{url_for('users.search')}}">
          <input
            name="search_username"
            type="text"
            style="border-radius: 4px; border-style: solid; border-width: 1px;border-color: #d3d3dd;  outline: none; text-align: center; font-size: 15px; color: #393939;margin: 0 1vw 0 0vw; background-color: #fafafa;"
            placeholder="Search"
            onfocus="this.placeholder = ''"
            onblur="this.placeholder='Search'"
          />
        </form>
      </div>
      <div style="display: flex; flex-direction: row;">
        {% if current_user.is_authenticated %}

        <a
          class="google_sign_in"
          href="{{url_for('sessions.login_with_google')}}"
        >
          <p>
            Google
          </p>
        </a>
        <a href="{{url_for('users.show', username = current_user.username)}}"
          ><img
            src="/static/images/people_icon.png"
            style="margin: 0 2vw 0vh 0; width: 35px; height: 40px; padding: 0 0 1vh 0;"
            alt="People icon"
        /></a>

        <form action="{{url_for('sessions.delete')}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
          <button
            type="submit"
            style="margin: 0 1vw 0 0 ; border: none; color: #007BFF; cursor: pointer;outline: none;"
          >
            <img
              src="/static/images/logout.png"
              alt="logout_icon"
              style="width: 25px; height: 25px;"
            />
          </button>
          <a href="{{url_for('users.show', username = current_user.username)}}">
            <img
              src="{{current_user.image_path}}"
              alt="Profile image"
              style="width: 30px; height: 30px; border-radius: 50%; margin: 0 0vw 0 0;cursor: pointer;"
            />
          </a>
        </form>

        {%else %}
        <a href="{{url_for('sessions.new')}}">
          <p style="margin: 0 2vw 0 0;">Login</p>
        </a>
        <a href="{{url_for('users.new')}}">
          <p>Sign Up</p>
        </a>
        {% endif%}
      </div>
    </nav>

    {% endblock %} {% with messages = get_flashed_messages() %} {% if messages
    %} {% for message in messages %}
    <p style="margin: 2vh 0 0 5vw; color: #ed4956;">{{ message }}</p>
    {% endfor %} {% endif %} {% endwith %}
    <div style="padding: 8.5vh 0 0 0;">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

instagram_web/templates/home.html
{% extends "_layout.html" %} {% block title %} {% endblock %} {% block content
%}
<div
  style="background-color: #fafafa; height: 100vh; width: 100vw; padding: 6vh 0 0 9vw;"
>
<!-- Follower Post -->
{%for f in allfollowers%}
{%if f.profile.user_posts | length > 0 %}
  <div
    style="width: 53vw; height: 70vh; background-color: white;border: 1px solid #c2c2c2; border-radius: 4px; display: flex; flex-direction: column; margin: 0 0 10vh 0 ;"
  >
    <div style="display: flex;flex-direction: row; margin: 1vh 0 1vh 1vw;">
      <div style="background: linear-gradient(to bottom right, #6600cc 10%, #ff6600 90%); width: 32px;height: 32px; border-radius: 50%; justify-content: center;text-align: center;align-items: center;line-height: 30px;">

        <img
          src="{{f.profile.image_path}}"
          alt=""
          style="width: 30px;height: 30px; border-radius: 50%;"
        />
        
      </div>
      <div style="display: flex;flex-direction: column;">
        <a
          href="{{url_for('users.show', username = f.profile.username)}}"
          style="color: black;text-decoration: none;"
        >
          <p style="margin: 0.5vh 0vw 0 0.5vw; font-size: 12px;">
            {{f.profile.username}}
          </p>
        </a>
      </div>
    </div>
    <img
      src="{{f.profile.user_posts[0].image_path}}"
      alt=""
      style="width: 100%; height: 45vh;object-fit: cover;"
    />
    <div style="border-bottom: 1px solid #c2c2c2;height:11vh">
      <div
        style="display: flex;flex-direction: row; margin: 1.5vh 0 0 1vw; justify-content: space-between;"
      >
        <div>
          <img
            src="/static/images/like_icon2.png"
            alt=""
            style="height: 25px; width: 25px; cursor: pointer;"
          />
          <img
            src="/static/images/comment_icon copy.png"
            alt=""
            style="height: 28px; width: 28px;margin: 0 0 0 0.5vw; cursor: pointer"
          />
        </div>
        <div style="margin: 0 1vw 0 0;">
          <img
            src="/static/images/bookmark.png"
            alt=""
            style="height: 25px; width: 25px;margin: 3px 0px 0 0; cursor: pointer"
          />
        </div>
      </div>
      <div style="margin: 0.3vh 0 0 1vw;font-size: 14px;color: #c2c2c2;">Posted on {{f.profile.user_posts[0].created_at.strftime('%b %d %Y')}}</div>
    </div>
    <div><input / style="width: 52vw;outline: none; border: none; height: 7vh; color: #c2c2c2; padding:0 0 0 1vw; font-size: 15px;" placeholder="Add a comment.."
      onfocus="this.placeholder = ''"
      onblur="this.placeholder='Add a comment...'"
      ></div>
  </div>
  {%endif%}
  {%endfor%}
  <!-- Profile Icon and Profile username -->
  <div
    style=" position: fixed; top:14%; left: 64%; display: flex; flex-direction: row;"
  >
    <a href="{{url_for('users.show', username = current_user.username)}}">
      <img
        src="{{current_user.image_path}}"
        alt="profile picture"
        style="width: 45px;height: 45px;border-radius: 50%; cursor: pointer;"
      />
    </a>
    <div style="display: flex; flex-direction: column;">
      <p style="margin: 0 0 0 0.5vw; font-size: 15px;">
        {{current_user.username}}
      </p>
      <p style="margin: 0 0 0 0.5vw; color: #c2c2c2;font-size: 13px;">
        {{current_user.name}}
      </p>
    </div>
  </div>
  <!-- Follower Stories -->
  <div
    style="background-color: white; border: 1px solid #c2c2c2; width: 20vw; height: 32vh; position: fixed; top:22%; left: 64%;border-radius: 4px; display: flex;flex-direction: column;"
  >
    <div
      style="display: flex; flex-direction: row;justify-content: space-between; padding: 1vh 1vw 0 1vw;"
    >
      <p style="font-size: 14px;color: #a1a1a1;">Stories</p>
      <p style="font-size: 14px;cursor: pointer;">Watch All</p>
    </div>
    <div style="overflow-y: scroll;">
      {% for f in allfollowers%}
      <div style="display: flex;flex-direction: row;margin: 0 0 1.5vh 0.75vw;">
        <div style="background: linear-gradient(to bottom right, #6600cc 10%, #ff6600 90%); width: 40px;height: 40px; border-radius: 50%; justify-content: center;text-align: center;align-items: center;line-height: 38px;">
          <a href="{{url_for('users.show',username = f.profile.username)}}">

            <img
              src="{{f.profile.image_path}}"
              alt=""
              style="width: 38px;height: 38px;cursor: pointer;border-radius: 50%;"          
            />
          </a>
        </div>

        <div style=" display: flex; flex-direction: column;">
          <p style="margin: 0 0 0 0.5vw ;font-size: 14px;">{{f.profile.username}}</p style="margin: 0 0 0 0 ;">
          <p style="margin: 0 0 0 0.5vw ;font-size: 12px; color: #c2c2c2;">{{f.profile.name}}</p style="margin: 0 0 0 0 ;">
         
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
  <!-- Friend suggestion -->
  <div style="background-color: white;border: 1px solid #c2c2c2; width: 20vw; height: 28.5vh; position: fixed; top: 56%; left: 64%; border-radius: 4px; display: flex; flex-direction: column;">
    <div style="display: flex; flex-direction: row; padding: 1vh 1vw 0 1vw;">
      <p style="color: #a1a1a1; font-size: 13px;">Suggestions For You</p>
    </div>
    {%for p in current_user.my_not_following[:3]%}
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <div style="display: flex;flex-direction: row;margin: 0 0 1.5vh 0.75vw;">
        <div style="background: linear-gradient(to bottom right, #6600cc 10%, #ff6600 90%); width: 40px;height: 40px; border-radius: 50%; justify-content: center;text-align: center;align-items: center;line-height: 38px;">
          <a href="{{url_for('users.show',username = p.username)}}">

            <img
              src="{{p.image_path}}"
              alt=""
              style="width: 38px;height: 38px;cursor: pointer;border-radius: 50%;"          
            />
          </a>
        </div>
        <div style=" display: flex; flex-direction: column;">
          <p style="margin: 0 0 0 0.5vw ;font-size: 14px;">{{p.username}}</p style="margin: 0 0 0 0 ;">
          <p style="margin: 0 0 0 0.5vw ;font-size: 12px; color: #c2c2c2;">{{p.name}}</p style="margin: 0 0 0 0 ;">
        </div>
      </div>
      <div style="margin: 0 1vw 0 0; padding: 1vh 0 0 0;">
       <form action="{{url_for('users.follow', username=p.username)}}" method="POST">
         <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
         <button style="cursor: pointer;font-size: 14px; margin: 0; background: none;border: none;color: #3897f0;cursor: pointer;">
            Follow
         </button>
        </form>  
      </div>
    </div>
    {%endfor%}
  </div>
{% endblock %}