instagram_web/blueprints/payment/views.py
import os
from flask import Blueprint, render_template,request,url_for,redirect, flash
from werkzeug.security import generate_password_hash, check_password_hash
from models.payment import *
from models.user import *
from models.user_images import *
from flask_wtf.csrf import CSRFProtect
from flask_login import current_user
from app import gateway
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

payment_blueprint = Blueprint('payment',
                            __name__,
                            template_folder='templates')


@payment_blueprint.route("/payment/<img_id>", methods=["GET"])
def new_payment(img_id):
    client_token = gateway.client_token.generate({})

    return render_template('payment/new.html', client_token = client_token, img_id= img_id)

@payment_blueprint.route("/payment/<img_id>", methods=["POST"])
def payment(img_id):
    nonce = request.form.get("nonce")
    amount = request.form.get("amount")
    message = request.form.get("message")

    result = gateway.transaction.sale({
        "amount": amount,
        "payment_method_nonce": nonce,
        "options": {
        "submit_for_settlement": True
        }
    })



    if result.is_success:
        new_donation = Payment(user=current_user.id,image=img_id, amount=amount, message=message)

        if new_donation.save():
            image = User_images.get_or_none(id = img_id)
            image_owner = User.get_or_none(id = image.user_id)
            
            message = Mail(
                from_email='NazNextagram@gmail.com',
                to_emails="nazrin2222@gmail.com",
                subject="You've received a donation!",
                html_content=render_template("payment/email_template.html", amount = amount))
            try:
                sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
                response = sg.send(message)
                print(response.status_code)
                print(response.body)
                print(response.headers)
            except Exception as e:
                print(e.message)

            return redirect(url_for('home'))
        else:
            return render_template('payment/new.html')
    else:
        flash("something went wrong")
        return render_template('payment/new.html')
    
        

instagram_web/blueprints/payment/templates/payment/email_template.html
<div
  style="background-color: #94d0ff; width: 100%; margin: 0; height: 20vh; padding: 0;"
>
  <div style="text-align: center; line-height: 20vh;">
    <h1 style="margin: 0;">
      You have receive a donation!
    </h1>
  </div>
</div>

<div
  style="background-color:#ed4956; width: 100%; margin: 0; height: 30vh; padding: 0;"
>
  <div style="text-align: center; line-height: 30vh;">
    <p style="font-size: 20px; margin: 0; color: white ;">
      Your image has received a donation from {{current_user.username}} of
      amount ${{amount}}
    </p>
  </div>
</div>

instagram_web/blueprints/payment/templates/payment/new.html
{% extends '_layout.html' %} {%block navbar%} {%endblock%} {%block content%}
<style>
  .currencyinput {
    border: 1px inset #ccc;
  }
  .currencyinput input {
    border: 0;
  }
</style>
<h1>Payment</h1>
<script src="https://js.braintreegateway.com/web/dropin/1.22.0/js/dropin.min.js"></script>

<div style="margin: 0 5vw 0 5vw;">
  <div id="dropin-container"></div>

  <form
    id="123"
    action="{{url_for('payment.payment', img_id = img_id)}}"
    method="POST"
    onsubmit="return false"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="hidden" name="nonce" id="nonce" />
    <label for="amount">Donation amount</label>

    <button
      type="button"
      style="width: 50px; border-radius: 4px;cursor: pointer;"
      id="button5"
    >
      5
    </button>
    <button
      type="button"
      style="width: 50px; border-radius: 4px;cursor: pointer;"
      id="button10"
    >
      10
    </button>

    <button
      type="button"
      style="width: 50px; border-radius: 4px;cursor: pointer;"
      id="button20"
    >
      20
    </button>
    <button
      type="button"
      style="width: 50px; border-radius: 4px;cursor: pointer;"
      id="button50"
    >
      50
    </button>

    <div style="display: flex; flex-direction: column;">
      <span class="currenct_input"
        >$
        <input
          type="number"
          name="amount"
          id="amount"
          style="width: 250px; border-radius: 4px; border-style: solid; border-width: 1px;border-color: #d3d3d3; margin: 2vh 0 0 0 ;"
          placeholder="Some other amount"
        />
      </span>
      <label for="message" style="margin: 2vh 0 0 0 ;"> Donation Message</label>
      <textarea
        name="message"
        rows="10"
        placeholder="Say something..."
        style=" border-radius: 4px; border-style: solid; border-width: 1px;border-color: #d3d3d3; height: 150px"
      ></textarea>
    </div>
    <button
      type="submit"
      id="submit-button"
      style="margin: 2vh 0 0 0; border-radius: 4px; cursor: pointer;"
    >
      Donate
    </button>
  </form>
</div>
<script>
  var button = document.querySelector("#submit-button");

  braintree.dropin.create(
    {
      authorization: "{{client_token}}",
      container: "#dropin-container"
    },
    function(createErr, instance) {
      button.addEventListener("click", function() {
        instance.requestPaymentMethod(function(err, payload) {
          console.log(payload.nonce);
          document.getElementById("nonce").value = payload.nonce;
          document.getElementById("123").submit();
        });
      });
    }
  );

  let button5 = document.querySelector("#button5");

  button5.addEventListener("click", function() {
    document.getElementById("amount").value = 5;
  });

  let button10 = document.querySelector("#button10");

  button10.addEventListener("click", function() {
    document.getElementById("amount").value = 10;
  });

  let button20 = document.querySelector("#button20");

  button20.addEventListener("click", function() {
    document.getElementById("amount").value = 20;
  });

  let button50 = document.querySelector("#button50");

  button50.addEventListener("click", function() {
    document.getElementById("amount").value = 50;
  });
</script>

{%endblock%}